# Generated by Django 4.2.5 on 2023-10-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0002_note_user_tag_user_alter_tag_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('text', models.TextField()),
            ],
        ),
    ]
