[tool.poetry]
name = "pw1410"
version = "0.1.0"
description = ""
authors = ["Oleksandr Martyniuk <sasha.martynuk.1@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
